2021-07-26 10:03:46,897 ERROR: Exception on /search [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\main\routes.py", line 179, in search
    return render_template(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\microblog\app\templates\search.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\py\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "d:\py\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\py\microblog\app\templates\base.html", line 57, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\py\microblog\app\templates\search.html", line 5, in block 'app_content'
    <p>{{ _('Searching for "%(q)s"')}}</p>
  File "d:\py\microblog\venv\lib\site-packages\jinja2\ext.py", line 168, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\ext.py", line 180, in gettext
    return rv % variables  # type: ignore
  File "d:\py\microblog\venv\lib\site-packages\markupsafe\__init__.py", line 109, in __mod__
    return self.__class__(super().__mod__(arg))
  File "d:\py\microblog\venv\lib\site-packages\markupsafe\__init__.py", line 263, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'q'
2021-07-26 10:05:33,773 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
2021-07-26 10:08:24,919 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
2021-07-26 10:08:57,712 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:90]
