2021-07-22 23:37:55,178 ERROR: Exception on /login [GET] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\py\microblog\app\routes.py", line 80, in login
    return render_template(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\microblog\app\templates\login.html", line 2, in top-level template code
    {% import 'boostrap/wtf.html' as wtf %}
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "d:\py\microblog\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: boostrap/wtf.html
2021-07-22 23:38:54,470 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:59]
2021-07-22 23:43:15,135 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:59]
2021-07-22 23:48:03,256 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:59]
2021-07-23 00:04:39,261 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:61]
2021-07-23 00:13:24,679 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:61]
2021-07-23 00:15:18,930 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:61]
2021-07-23 11:03:58,276 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 11:05:03,789 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 11:06:40,264 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 11:10:55,957 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 11:11:12,940 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 11:59:41,787 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:00:37,341 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:46:02,498 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:46:44,517 ERROR: Exception on /index [POST] [in d:\py\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\microblog\app\routes.py", line 33, in index
    post = Post(body=form.post.data, author=current_user, language=language)
  File "<string>", line 4, in __init__
  File "d:\py\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 480, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "d:\py\microblog\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "d:\py\microblog\venv\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "d:\py\microblog\venv\lib\site-packages\sqlalchemy\orm\state.py", line 477, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "d:\py\microblog\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1142, in _declarative_constructor
    raise TypeError(
TypeError: 'language' is an invalid keyword argument for Post
2021-07-23 12:49:40,456 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:49:50,159 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:51:13,413 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:51:37,811 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:52:04,380 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:52:28,971 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 12:53:50,922 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:07:00,970 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:20:49,288 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:26:54,577 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:27:53,707 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:40:46,439 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:41:48,196 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
2021-07-23 13:47:37,074 INFO: Microblog startup [in D:\py\microblog\app\__init__.py:64]
